#!/system/bin/sh

# Bind internal SD to some usual mount pints

for i in $(seq 1 1 60)
do
  if [ -e /data/media/0 ]; then
    mount -o remount,rw /
    mkdir /storage/sdcard1
    mkdir /mnt/extSdCard
    mount -o bind /data/media/0 /storage/sdcard1
    mount -o bind /data/media/0 /mnt/extSdCard
    chmod 0777 /storage/sdcard1
    chmod 0777 /mnt/extSdCard
    mount -o remount,ro /
    break;
  fi
  usleep 500000
done

